[package]
name = "uefi-async-macros"
version = "0.1.2"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full", "visit"] }
quote = "1.0"
proc-macro2 = "1.0"
darling = "0.23.0"